services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.20-ubi9
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - "27017:27017"