services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"